# Generated by Django 4.2.7 on 2023-11-29 11:01

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(
                default="Recipes_images/default.jpeg",
                null=True,
                upload_to=main_app.models.unique_img_name,
            ),
        ),
    ]
